stages:
 - test
 - visualize
 - package
 - install

test-java-job:
 stage: test
 image: maven:3.6.2-jdk-11
 script:
  - mvn $MAVEN_CLI_OPTS clean org.jacoco:jacoco-maven-plugin:prepare-agent test jacoco:report
 artifacts:
  paths:
   - target/site/jacoco/jacoco.xml

coverage-jdk11:
 stage: visualize
 image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
 script:
  - python /opt/cover2cover.py target/site/jacoco/jacoco.xml $CI_PROJECT_DIR/src/main/java/ > target/site/cobertura.xml
 needs: ["test-java-job"]
 artifacts:
  reports:
   cobertura: target/site/cobertura.xml

package-java-job:
 stage: package
 image: maven:3.6.2-jdk-11
 script:
  - mvn package -DskipTests
 artifacts:
  paths: 
   - target/Adresse-1.0-SNAPSHOT
  expire_in: 1 hour

install-image-job:
  stage: install
  dependencies:
   - package-java-job
  services:
   - docker:19.03.12-dind
  variables:
   CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
   DOCKER_TLS_CERTDIR: "/certs"
  before_script:
   - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  image: docker:19.03.12
  script:
   - docker build -t $CONTAINER_IMAGE:latest .
   - docker push $CONTAINER_IMAGE:latest
